sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: web-smh
    directory: sky-take-out

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

  wechat:
    appid: wxbf610674b8801ea4
    secret: 9fb449db26557d63bcab373c8dde5184

